# Generated by Django 4.1.5 on 2023-03-08 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_negocio', models.CharField(choices=[('ropa', 'Ropa'), ('detalles', 'Detalles'), ('salud', 'Salud'), ('automotriz', 'Automotriz'), ('comida', 'Comida'), ('belleza', 'Belleza'), ('otro', 'Otro')], default='otro', max_length=15)),
                ('nombre_negocio', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('direccion', models.CharField(max_length=250)),
                ('horario', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=200)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('fecha_publicacion', models.DateField()),
                ('imagen_negocio', models.ImageField(upload_to='')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaCalificacion', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='AppDirectorio.negocio')),
            ],
        ),
    ]
