# Generated by Django 4.1.5 on 2023-03-10 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppDirectorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaCalificacion', models.DateTimeField()),
                ('negocio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='AppDirectorio.negocio')),
            ],
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
    ]
